# Generated by Django 4.0.4 on 2022-04-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemplanner_poc', '0002_poecharacterclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='POECharSkillGemMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_gem_id', models.IntegerField()),
                ('class_id', models.IntegerField()),
                ('min_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='POEQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='poeskillgem',
            name='gemtype',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
